### ISSUE TITLE
404 on GET /gwc/workflows/meta

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-editor-fe#4]
request:

GET /gwc/workflows/meta HTTP/1.0
Host: localhost:9102
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Referer: https://data.dev.gawati.org/
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9,de-DE;q=0.8,de;q=0.7
Cookie: __utmz=64324537.1510238216.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.972252038.1510238216; __utma=64324537.97
2252038.1510238216.1516358435.1516363427.16; _gid=GA1.2.16597271.1524572626
X-Forwarded-For: 109.164.203.165
X-Forwarded-Host: data.dev.gawati.org
X-Forwarded-Server: data.dev.gawati.org

-----

response:

HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'self'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1898
Date: Wed, 25 Apr 2018 08:43:17 GMT
Connection: close

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Not Found<br> &nbsp; &nbsp;at /home/gawatidevclientsrv/portal/app.js:51:15<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/gawatidevclie
ntsrv/portal/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/ind
ex.js:317:13)<br> &nbsp; &nbsp;at /home/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/h
ome/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/home/gawatidevclientsrv/portal/node_modules/express/li
b/router/index.js:275:10)<br> &nbsp; &nbsp;at /home/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:635:15<br> &nbsp; &nbsp;at next (/home/ga
watidevclientsrv/portal/node_modules/express/lib/router/index.js:260:14)<br> &nbsp; &nbsp;at Function.handle (/home/gawatidevclientsrv/portal/node_modules/expre
ss/lib/router/index.js:174:3)<br> &nbsp; &nbsp;at router (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:47:12)<br> &nbsp; &nbsp;at La
yer.handle [as handle_request] (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/gawatidevc
lientsrv/portal/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /home/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:28
4:7<br> &nbsp; &nbsp;at Function.process_params (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/hom
e/gawatidevclientsrv/portal/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at /home/gawatidevclientsrv/portal/node_modules/express/lib/router
/index.js:635:15</pre>
</body>
</html>

**Comment by kohsah** [comment]
@ccsmart  thats weird, i am on `dev`:

```
$ curl http://localhost:9002/gwc/workflows/meta
[{"doctype":"act","subtype":"legge","status":"valid"},{"doctype":"judgment","subtype":"courtjudgment","status":"valid"}]
```

**Comment by ccsmart** [comment]
Jenkins designates it as efb71298e6f9f7e0d080ca93b9fcea0da110aae1, which would be current atm

**Comment by ccsmart** [comment]
one might think so, but indeed thats what we got on the server:
[root@alldev portal]# pwd
/home/gawatidevclientsrv/portal
[root@alldev portal]# cat app.js | sed -n '48,54p'

app.use("/gwc", routes);


// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error("Not Found");
[root@alldev portal]#

so appears not out of date.
your credentials still work ?

**Comment by kohsah** [comment]
@ccsmart i believe this is not happening anymore ?

**Comment by ccsmart** [comment]
Root cause was failure of post update restart of the service.
